import { Injectable, signal, inject } from '@angular/core';
import { Router } from '@angular/router';

export type Lang = 'fr' | 'en';

type Dict = Record<string, string>;

const FR: Dict = {
  'nav.about': 'À PROPOS',
  'nav.skills': 'COMPÉTENCES',
  'nav.experience': 'EXPÉRIENCES',
  'nav.projects': 'PROJETS',
  'nav.github': 'GITHUB',

  'hero.availability': 'DISPONIBLE · DÉVELOPPEUR WEB FULLSTACK',
  'hero.subtitle': 'Diplômé Master MIAGE · Orléans',
  'hero.specialityPrefix': 'Spécialisé en',
  'hero.specialityAnd': '&',
  'hero.viewPath': 'Voir mon parcours',
  'hero.downloadCv': 'Télécharger le CV',
  'stats.experience': "ans d'alternance",
  'stats.technologies': 'technologies',
  'stats.projects': 'projets réalisés',

  'chat.title': 'Assistant IA',
  'chat.idlePrompt': 'Posez-moi une question<br />sur le parcours de Kong-Meng !',
  'chat.thinking': 'En train de réfléchir...',
  'chat.talking': "En train d'écrire...",
  'chat.placeholder': 'Écrivez votre question...',
  'chat.note': 'Réponses générées par IA',
  'chat.greeting': 'Bonjour ! Je suis votre assistant IA. Posez-moi une question sur le parcours, les compétences ou les projets de Kong-Meng.',
  'chat.noAnswer': "Je n'ai pas reçu de réponse.",
  'chat.error': 'Erreur : impossible de contacter le backend.',
  'chat.expand': 'Agrandir le chat',
  'chat.collapse': 'Réduire le chat',

  'skills.label': 'COMPÉTENCES TECHNIQUES',
  'skills.title': 'Mon stack',
  'skill.frontend': 'Frontend',
  'skill.backend': 'Backend',
  'skill.base_de_donnees': 'Base de données',
  'skill.lowcode': 'Low-Code',
  'skill.outils': 'Outils',
  'skill.methodologies': 'Méthodologies',

  'experience.label': 'PARCOURS PROFESSIONNEL',
  'experience.title': 'Expériences',
  'education.title': 'Master MIAGE – Mention assez bien',
  'education.school': "Université d'Orléans – UFR Sciences & Techniques",
  'education.badge': 'Formation',
  'education.period': '2022 – 2025',
  'education.location': 'Orléans',
  'education.mission1': 'Méthodes Informatiques Appliquées à la Gestion des Entreprises',
  'education.mission2': 'Formation en alternance : développement web, gestion de projet, systèmes d\'information',

  'projects.label': 'PROJETS RÉALISÉS',
  'projects.title': 'Quelques projets',

  'footer.copyright': '© 2026 Kong-Meng Yang',

  'detail.back': 'Retour au portfolio',
  'detail.viewGithub': 'Voir sur GitHub',
  'detail.viewSite': 'Voir le site →',
  'detail.privateBadge': '🔒 Dépôt de code privé',
  'detail.confidentialBadge': '🔒 Projet confidentiel – réalisé en entreprise',
  'detail.roleContext': 'Rôle & contexte',
  'detail.roleLabel': 'Rôle :',
  'detail.contextLabel': 'Contexte :',
  'detail.about': 'À propos du projet',
  'detail.results': 'Résultats & impact',
  'detail.technologies': 'Technologies utilisées',
  'detail.screenshots': "Captures d'écran",
  'detail.privateTitle': 'Dépôt de code privé',
  'detail.privateText': "Ce projet a été réalisé en groupe dans le cadre de ma formation. Le dépôt de code est privé, mais je peux en parler en détail sur demande.",
  'detail.confidentialTitle': 'Projet réalisé en entreprise',
  'detail.confidentialText': "Ce projet a été développé dans un environnement professionnel. Les captures d'écran et détails sensibles ont été volontairement omis pour respecter la confidentialité.",
  'detail.notFound': 'Projet introuvable',
  'detail.backButton': 'Retour',
  'detail.loadError': 'Impossible de charger les projets',
  'detail.loadErrorText': "Le serveur ne répond pas (vérifie qu'il est bien démarré et accessible).",
};

const EN: Dict = {
  'nav.about': 'ABOUT',
  'nav.skills': 'SKILLS',
  'nav.experience': 'EXPERIENCE',
  'nav.projects': 'PROJECTS',
  'nav.github': 'GITHUB',

  'hero.availability': 'AVAILABLE · FULLSTACK WEB DEVELOPER',
  'hero.subtitle': "Master's degree (MIAGE) · Orléans, France",
  'hero.specialityPrefix': 'Specialized in',
  'hero.specialityAnd': '&',
  'hero.viewPath': 'View my background',
  'hero.downloadCv': 'Download CV',
  'stats.experience': 'years of experience',
  'stats.technologies': 'technologies',
  'stats.projects': 'projects delivered',

  'chat.title': 'AI Assistant',
  'chat.idlePrompt': "Ask me a question<br />about Kong-Meng's background!",
  'chat.thinking': 'Thinking...',
  'chat.talking': 'Typing...',
  'chat.placeholder': 'Type your question...',
  'chat.note': 'Answers generated by AI',
  'chat.greeting': "Hello! I'm your AI assistant. Ask me a question about Kong-Meng's background, skills or projects.",
  'chat.noAnswer': "I didn't receive an answer.",
  'chat.error': 'Error: unable to reach the backend.',
  'chat.expand': 'Expand chat',
  'chat.collapse': 'Collapse chat',

  'skills.label': 'TECHNICAL SKILLS',
  'skills.title': 'My stack',
  'skill.frontend': 'Frontend',
  'skill.backend': 'Backend',
  'skill.base_de_donnees': 'Databases',
  'skill.lowcode': 'Low-Code',
  'skill.outils': 'Tools',
  'skill.methodologies': 'Methodologies',

  'experience.label': 'PROFESSIONAL BACKGROUND',
  'experience.title': 'Experience',
  'education.title': "Master's degree (MIAGE) – Honors",
  'education.school': 'University of Orléans – UFR Sciences & Techniques',
  'education.badge': 'Education',
  'education.period': '2022 – 2025',
  'education.location': 'Orléans, France',
  'education.mission1': 'Applied Computer Methods for Business Management',
  'education.mission2': 'Work-study program: web development, project management, information systems',

  'projects.label': 'FEATURED PROJECTS',
  'projects.title': 'Some of my projects',

  'footer.copyright': '© 2026 Kong-Meng Yang',

  'detail.back': 'Back to portfolio',
  'detail.viewGithub': 'View on GitHub',
  'detail.viewSite': 'View site →',
  'detail.privateBadge': '🔒 Private code repository',
  'detail.confidentialBadge': '🔒 Confidential – built in a professional environment',
  'detail.roleContext': 'Role & context',
  'detail.roleLabel': 'Role:',
  'detail.contextLabel': 'Context:',
  'detail.about': 'About this project',
  'detail.results': 'Results & impact',
  'detail.technologies': 'Technologies used',
  'detail.screenshots': 'Screenshots',
  'detail.privateTitle': 'Private code repository',
  'detail.privateText': "This project was built as a group during my studies. The code repository is private, but I'm happy to talk through it in detail on request.",
  'detail.confidentialTitle': 'Built in a professional environment',
  'detail.confidentialText': "This project was developed in a professional environment. Screenshots and sensitive details were intentionally omitted to respect confidentiality.",
  'detail.notFound': 'Project not found',
  'detail.backButton': 'Back',
  'detail.loadError': 'Unable to load projects',
  'detail.loadErrorText': "The server isn't responding (check that it's running and reachable).",
};

const DICT: Record<Lang, Dict> = { fr: FR, en: EN };

@Injectable({ providedIn: 'root' })
export class I18nService {
  private router = inject(Router);

  lang = signal<Lang>('fr');

  /** Detects the language to use on first visit: stored preference, else browser language. */
  detect(): Lang {
    try {
      const stored = localStorage.getItem('lang');
      if (stored === 'fr' || stored === 'en') return stored;
    } catch {}
    const nav = (typeof navigator !== 'undefined' ? navigator.language : '') || '';
    return nav.toLowerCase().startsWith('fr') ? 'fr' : 'en';
  }

  /** Syncs the signal from a route param without navigating (called on route activation). */
  sync(langParam: string | null): void {
    const resolved: Lang = langParam === 'en' ? 'en' : 'fr';
    if (this.lang() !== resolved) {
      this.lang.set(resolved);
    }
    try { localStorage.setItem('lang', resolved); } catch {}
  }

  /** Switches language and navigates to the equivalent URL under the new lang prefix. */
  switchTo(newLang: Lang): void {
    if (newLang === this.lang()) return;
    this.lang.set(newLang);
    try { localStorage.setItem('lang', newLang); } catch {}
    const rest = this.router.url.replace(/^\/(fr|en)/, '');
    this.router.navigateByUrl(`/${newLang}${rest}`);
  }

  t(key: string): string {
    return DICT[this.lang()][key] ?? key;
  }
}
